# Generated by Django 5.2.3 on 2025-06-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload foto profil Anda', null=True, upload_to='cv_photos/'),
        ),
    ]
