# Generated by Django 5.2.3 on 2025-06-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_cv_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.TextField(blank=True, help_text='Alamat lengkap', null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='city',
            field=models.CharField(blank=True, help_text='Kota', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='country',
            field=models.CharField(blank=True, help_text='Negara', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='github',
            field=models.URLField(blank=True, help_text='Link GitHub', null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='instagram',
            field=models.URLField(blank=True, help_text='Link Instagram', null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Link LinkedIn', null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.CharField(blank=True, help_text='Nomor telepon', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='portfolio',
            field=models.URLField(blank=True, help_text='Link portfolio', null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='twitter',
            field=models.URLField(blank=True, help_text='Link Twitter/X', null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='website',
            field=models.URLField(blank=True, help_text='Website pribadi', null=True),
        ),
    ]
